import React from "react"
import { Inter } from "next/font/google"
import "./globals.css"
import PropTypes from "prop-types"
import Providers from "@/src/components/Providers"
import appConfig from "@/app.config"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: appConfig.PROJECT_NAME,
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/positsource_logo.jpg" />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
}
